import { chromium } from 'file:///C:/Users/fplev/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
const page = await browser.newPage({ viewport: { width: 1100, height: 900 }, reducedMotion: 'no-preference' });
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
await page.route('**/src/main.js',async route=>{
  const response=await route.fetch();
  const body=await response.text();
  await route.fulfill({response,body:body+`
window.__completeCampaign = () => {
  mode='story'; selected=characterFor('clariana'); story=new Story('clariana',()=>0.5);
  const result=(groups)=>({players:story.participants().map(player=>({...player,alive:player.id==='human'})),eliminationGroups:groups,winner:'human'});
  for(let i=0;i<3;i++) story.resolve(result(story.participants().filter(player=>player.bot).map(player=>[player.id])));
  story.resolve(result([['flavio'],['lula']]));
  match=new Match({players:story.participants()}); phase='playing'; showScreen('game');
  finishStory(result(story.participants().filter(player=>player.bot).map(player=>[player.id])));
};
`});
});
await page.goto('http://localhost:4185');
await page.evaluate(()=>window.__completeCampaign());
assert.equal(await page.locator('body').getAttribute('data-screen'),'victory');
await page.screenshot({path:'.scratch/victory-scene/arrival.png',fullPage:true});
await page.locator('#victory-message').waitFor({state:'visible',timeout:12000});
assert.equal(await page.locator('#victory-message').textContent(),'Quem diria? Você acabou com o ciclo do poder');
assert.equal(await page.locator('#victory-winner').textContent(),'Clariana Barão venceu');
await page.screenshot({path:'.scratch/victory-scene/complete.png',fullPage:true});
await page.locator('#victory-exit').click();
assert.equal(await page.locator('body').getAttribute('data-screen'),'home');
await page.goBack();
assert.equal(await page.locator('body').getAttribute('data-screen'),'victory');
assert.equal(await page.locator('#victory-message').isVisible(),false);
await page.locator('#victory-exit').click();
await page.emulateMedia({reducedMotion:'reduce'});
await page.evaluate(()=>window.__completeCampaign());
assert.equal(await page.locator('#victory-message').isVisible(),true);
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'.scratch/victory-scene/mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.locator('#victory-restart').click();
assert.equal(await page.locator('body').getAttribute('data-screen'),'selection');
assert.equal(await page.locator('#mode-label').textContent(),'Modo história');
await page.goto('http://localhost:4185/#vitoria');
await page.reload();
assert.equal(await page.locator('body').getAttribute('data-screen'),'home');
assert.deepEqual(errors,[]);
console.log('Navegador: vitória real da campanha, conclusão da cena, Sair, Nova história, movimento reduzido, mobile e acesso direto verificados; zero erros.');
await browser.close();
